import type { MoveEntity } from './interface';

import {
  EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE,
  EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE,
  EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE,
  POKEMON_MOVE_INFORMATION_EXTERNAL_RESPONSE_CUT_FIXTURE,
  POKEMON_MOVE_INFORMATION_EXTERNAL_RESPONSE_RAZOR_WIND_FIXTURE,
  POKEMON_MOVE_INFORMATION_EXTERNAL_RESPONSE_SWORDS_DANCE_FIXTURE,
} from '../../../api/external/pokemon/modules';

export const MOVE_ENTITY_RAZOR_WIND_FIXTURE: MoveEntity = {
  id: 'fc6e1615-2061-4e44-95c2-270dabda7cf7',
  pp: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.pp,
  url: POKEMON_MOVE_INFORMATION_EXTERNAL_RESPONSE_RAZOR_WIND_FIXTURE.move.url,
  type: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.type.name,
  name: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.name,
  order: 13,
  power: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.power,
  target: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.target.name,
  effect:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.effect_entries[0]
      .effect,
  priority: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.priority,
  accuracy: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.accuracy,
  created_at: undefined,
  updated_at: undefined,
  deleted_at: undefined,
  short_effect:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.effect_entries[0]
      .short_effect,
  damage_class:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.damage_class.name,
  effect_chance:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_RAZOR_WIND_FIXTURE.effect_chance,
};
export const MOVE_ENTITY_SWORDS_DANCE_FIXTURE: MoveEntity = {
  id: '36d17828-61c1-448d-b596-c4da94b9ac16',
  pp: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.pp,
  url: POKEMON_MOVE_INFORMATION_EXTERNAL_RESPONSE_SWORDS_DANCE_FIXTURE.move.url,
  type: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.type.name,
  name: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.name,
  order: 14,
  power: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.power,
  target: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.target.name,
  effect:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.effect_entries[0]
      .effect,
  priority: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.priority,
  accuracy: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.accuracy,
  created_at: undefined,
  updated_at: undefined,
  deleted_at: undefined,
  short_effect:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.effect_entries[0]
      .short_effect,
  damage_class:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.damage_class.name,
  effect_chance:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_SWORDS_DANCE_FIXTURE.effect_chance,
};
export const MOVE_ENTITY_CUT_FIXTURE: MoveEntity = {
  id: '620458fb-26de-49af-b2ca-1428916c627d',
  pp: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.pp,
  url: POKEMON_MOVE_INFORMATION_EXTERNAL_RESPONSE_CUT_FIXTURE.move.url,
  type: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.type.name,
  name: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.name,
  order: 15,
  power: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.power,
  target: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.target.name,
  effect: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.effect_entries[0].effect,
  priority: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.priority,
  accuracy: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.accuracy,
  created_at: undefined,
  updated_at: undefined,
  deleted_at: undefined,
  short_effect:
    EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.effect_entries[0].short_effect,
  damage_class: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.damage_class.name,
  effect_chance: EXTERNAL_RESPONSE_OF_MOVE_BY_URL_CUT_FIXTURE.effect_chance,
};

export const MOVE_ENTITY_LIST_FIXTURE: Array<MoveEntity> = [
  MOVE_ENTITY_RAZOR_WIND_FIXTURE,
  MOVE_ENTITY_SWORDS_DANCE_FIXTURE,
  MOVE_ENTITY_CUT_FIXTURE,
];
