import {
  POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_CHLOROPHYLL_FIXTURE,
  POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_OVERGROW_FIXTURE,
} from '../../../api/external/pokemon/modules';

import type { AbilityEntity } from './interface';

export const ABILITY_ENTITY_OVERGROW_FIXTURE: AbilityEntity = {
  id: 'fc6e1615-2061-4e44-95c2-270dabda7cf7',
  url: POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_OVERGROW_FIXTURE.ability
    .url,
  name: POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_OVERGROW_FIXTURE.ability
    .name,
  slot: POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_OVERGROW_FIXTURE.slot,
  order: 65,
  is_hidden:
    POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_OVERGROW_FIXTURE.is_hidden,
  created_at: new Date('2024-12-17T03:01:22.577Z'),
  updated_at: new Date('2024-12-17T03:01:22.577Z'),
  deleted_at: undefined,
};

export const ABILITY_ENTITY_CHLOROPHYLL_FIXTURE: AbilityEntity = {
  id: 'fc6e1615-2061-4e44-95c2-270dabda7cf7',
  url: POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_CHLOROPHYLL_FIXTURE.ability
    .url,
  name: POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_CHLOROPHYLL_FIXTURE
    .ability.name,
  slot: POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_CHLOROPHYLL_FIXTURE.slot,
  order: 34,
  is_hidden:
    POKEMON_ABILITY_INFORMATION_EXTERNAL_RESPONSE_CHLOROPHYLL_FIXTURE.is_hidden,
  created_at: new Date('2024-12-17T03:01:22.577Z'),
  updated_at: new Date('2024-12-17T03:01:22.577Z'),
  deleted_at: undefined,
};

export const ABILITY_ENTITY_LIST_FIXTURE: Array<AbilityEntity> = [
  ABILITY_ENTITY_OVERGROW_FIXTURE,
  ABILITY_ENTITY_CHLOROPHYLL_FIXTURE,
];
