export type TIcon =
  | 'user'
  | 'lamp'
  | 'star'
  | 'info'
  | 'like'
  | 'exit'
  | 'check'
  | 'close'
  | 'error'
  | 'react'
  | 'phone'
  | 'google'
  | 'camera'
  | 'confirm'
  | 'success'
  | 'warning'
  | 'arrow-up'
  | 'facebook'
  | 'calendar'
  | 'document'
  | 'star-half'
  | 'dashboard'
  | 'hamburger'
  | 'arrow-down'
  | 'arrow-right'
  | 'star-filled'
  | 'arrow-up-outline'
  | 'arrow-down-outline';

export type TIconPosition = 'left' | 'right';
